---
    - name: "Install packages"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-server
        - python-setuptools
        - python3-pip
#        - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

    - name: creating alias
      shell: echo alias pip=pip3 >> ~/.bashrc

    - name: "Install Python packages"
      pip3:
        name: "{{ item }}"
        state: present
      with_items:
        - psycopg3-binary

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - postgresql

    - name: restart postgres
      service:
        name: postgresql
        state: restarted
