---
    - name: "Install epel repo"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release

    - name: "Install postgresql repo"
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: "Install packages"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql{{ pg_vers }}
        - postgresql{{ pg_vers }}-server
        - postgresql{{ pg_vers }}-devel
        - python-setuptools
        - python2-pip

    - name: "Install Python packages"
      pip:
        name: "{{ item }}"
        state: present
        executable: pip
      with_items:
        - psycopg2-binary

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/{{ pg_vers }}/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb || postgresql-{{ pg_vers }}-setup initdb"
#      become: yes
#      become_user: postgres
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - postgresql{{ pg_vers }}

    - name: restart postgres
      service:
        name: postgresql{{ pg_vers }}
        state: restarted

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
        create: true
      become: yes
      become_user: postgres

    - name: restart postgres
      service:
        name: postgresql{{ pg_vers }}
        state: restarted
