#TAGS:
# repo - create repos for postgresql
# packages - install postgresql server, pip2 and python libs
# init - check cluster initialisation state and init it if is not initialized
# service - start and enable postgresql service
# create - create database, user, grant access,
#          grant access in pg_hba, restart postgres
# postgres 10 is a minimal version for this role.
---
    - name: "Install epel repo"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
      tags: repo

    - name: "Install postgresql repo"
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
      tags: repo

    - name: "Install packages"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql{{ pg_vers }}
        - postgresql{{ pg_vers }}-server
        - python-setuptools
        - python2-pip
      tags: packages

    - name: "Install Python packages"
      pip:
        name: "{{ item }}"
        state: present
        executable: pip
      with_items:
        - psycopg2-binary
      tags: packages

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/{{ pg_vers }}/data/pg_hba.conf"
      register: postgres_data
      tags: init

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb || postgresql-{{ pg_vers }}-setup initdb"
      when: not postgres_data.stat.exists
      tags: init

    - name: "Start and enable services"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - postgresql-{{ pg_vers }}
      tags: service

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: postgres
      tags: create

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres
      tags: create

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres
      tags: create

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/{{ pg_vers }}/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
        create: true
      become: yes
      become_user: postgres
      tags: create

    - name: restart postgres
      service:
        name: postgresql-{{ pg_vers }}
        state: restarted
      tags: create
