---
    - name: Install tcpdump
      yum:
        name:
          - tcpdump
        state: present
        disable_gpg_check: yes
      tags:
        - packages

    - name: Copy config files to logrotate.d
      copy:
        src: files/logrotate-named-tcpdump
        dest: /etc/logrotate.d/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: Copy config files to sysconfig
      copy:
        src: files/named-tcpdump
        dest: /etc/sysconfig/
        owner: root
        group: root
        mode: 0744
      tags:
        - conf

    - name: Copy systemd service
      copy:
        src: files/named-tcpdump.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: daemon-reload and starting named-tcpdump
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: named-tcpdump
