---
    - name: Install tcpdump
      yum:
        name:
          - tcpdump
          - rsyslog
        state: present
        disable_gpg_check: yes
      tags:
        - packages

    - name: Copy config files to logrotate.d
      copy:
        backup: yes
        src: files/logrotate-named-tcpdump
        dest: /etc/logrotate.d/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: named-tcpdump service check
      stat:
        path: /etc/systemd/system/named-tcpdump.service
      register: namedtcpdumpstat

    - name: service named-tcpdump stop
      ansible.builtin.systemd:
        state: stopped
        name: "{{ item }}"
      with_items:
        - named-tcpdump
      when: namedtcpdumpstat.stat.exists

    - name: Copy config files to sysconfig
      copy:
        backup: yes
        src: files/named-tcpdump
        dest: /etc/sysconfig/
        owner: root
        group: root
        mode: 0744
      become: yes
      tags:
        - conf

    - name: Copy systemd service
      copy:
        backup: yes
        src: files/named-tcpdump.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: Copy rsyslog config
      template:
        backup: yes
        src: templates/named-tcpdump.conf.j2
        dest: /etc/rsyslog.d/named-tcpdump.conf
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: daemon-reload and starting named-tcpdump
      ansible.builtin.systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "{{ item }}"
      with_items:
        - named-tcpdump
        - rsyslog

    - name: tests
      include_tasks:
        file: tests.yml
