---
# tasks file for named-tcpdump
#- name: named-tcpdump
#  hosts: all
#  gather_facts: true
#
#  tasks:
    - name: Run a command using a templated variable (always use quote filter to avoid injection)
      ansible.builtin.shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf && ping -c 3 8.8.8.8 && ping -c 3 mail.ru

    - name: Install tcpdump
      yum:
        name:
          - tcpdump
        state: present
        disable_gpg_check: yes
      tags:
        - packages

    - name: Copy config files
      copy:
        src: files/named-tcpdump
        dest: /etc/sysconfig/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: Copy systemd service
      copy:
        src: files/named-tcpdump.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: Restart service named-tcpdump, daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: name-tcpdump
