---
    - name: Setup google dns
      command: echo "nameserver 8.8.8.8" > /etc/resolv.conf
      register: ls

    - name: Install epel
      yum:
        name:
          - epel-release
        state: present
        disable_gpg_check: yes
      tags:
        - packages

    - name: Install nfs client
      yum:
        name:
          - nfs-utils
          - libnfs-utils
        state: present
        disable_gpg_check: yes
      tags:
        - packages

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /media/nfs
        state: directory
        mode: '0755'

    - name: Enable and reload NFS client services
      ignore_errors: yes
      ansible.builtin.systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: "{{ item }}"
      with_items:
        - rpcbind
        - nfs-server
#        - nfs-lock
#        - nfs-idmap

    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 172.17.0.1:/home/nfs/
        path: /media/nfs
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
