---
    - name: New user add
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: "{{ item.shell }}"
      with_items: "{{ username }}"
#        name:
#          - {{ username.name }}
#        password: "{{ 'username.value.password' | password_hash('sha512') }}"
#        shell: "/bin/{{ 'username.value.shell' }}"
#        with_dict: "{{ username }}"
