---
    - name: New user add
      user:
        name:
          - "{{ item.name }}"
        password: "{{ 'item.password' | password_hash('sha512') }}"
        shell: "/bin/{{ 'item.shell' }}"
      register: useradd
      tags:
        - webserver_install
