---
    - name: New user add
      user:
        name:
          - "{{ item.key }}"
        password: "{{ 'item.value.password' | password_hash('sha512') }}"
        shell: "/bin/{{ 'item.value.shell' }}"
        with_dict: "{{ username }}"
