---
    - name: New user add
      user:
        name: {{ username }}
        password: "{{ 'username.password' | password_hash('sha512') }}"
        shell: /bin/{{ shell }}
      register: useradd
      tags:
        - webserver_install
