---
    - name: New user add
      user:
        name:
          - "{{ username }}"
        password: "{{ 'username.name.password' | password_hash('sha512') }}"
        shell: /bin/{{ username.name.shell }}
      register: useradd
      tags:
        - webserver_install
