---
    - name: New user add
      user:
        name:
          - "{{ username }} |string"
        password: "{{ 'username.password |string' | password_hash('sha512') }}"
        shell: /bin/{{ shell }}
      register: useradd
      tags:
        - webserver_install
