---
    - debug:
        msg:
          - "{{ username.user }}"
          - "{{ username.password }}"
          - "{{ username.shell }}"

    - name: New user add
      user:
        name:
          - "{{ username.user }}"
        password: "{{ 'username.password' | password_hash('sha512') }}"
        shell: "/bin/{{ 'username.shell' }}"
