---
    - name: Setup google dns
      command: echo "nameserver 8.8.8.8" > /etc/resolv.conf

    - name: Install bind 9.11
      yum:
        name:
          - bind
        state: present
        disable_gpg_check: yes
      tags:
        - packages

    - name: Copy config files to /etc
      copy:
        src: files/named.conf
        dest: /etc/
        owner: root
        group: root
        mode: 0644
      tags:
        - conf

    - name: Setup local dns
      command: echo "nameserver 127.0.0.1" > /etc/resolv.conf

    - name: daemon-reload, enabled, started
      ansible.builtin.systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: named
