---
    hostname: server1
    version: 7
    webserver: nginx
    username:
      - name: "taras"
        password: "taras"
        shell: "bash"
      - name: "sergey"
        password: "sergey"
        shell: "bash"
      - name: ivan
        password: ivan
        shell: bash
