---
    - name: "Add {{ webserver }} Repository"
      template: src={{ webserver }}.repo dest=/etc/yum.repos.d/ owner=root group=root
      register: webserver_repo
      tags:
        - Repository

    - name: Install webserver
      yum: pkg={{ webserver }} state=latest
      register: webserverinstalled
      tags:
        - webserver_install

    - name: "{{ webserver }} start"
      service: name={{ webserver }} state=started
      when: webserverinstalled.changed = 1
      tags:
        - webserver_start
