---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:centos7.6.1810
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_SCENARIO_DIRECTORY}/vault.pw"
verifier:
  name: ansible
