---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:centos7.6.1810
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }
provisioner:
  name: ansible
verifier:
  name: ansible
